perfectsense/gyro-azure-provider

- CHANGELOG.md
- build.gradle
- examples/.gyro/init.gyro
- examples/storage/storage-account.gyro
- src/main/java/gyro/azure/sql/SqlDatabaseResource.java
- src/main/java/gyro/azure/storage/PolicyAction.java
- src/main/java/gyro/azure/storage/PolicyBaseBlob.java
- src/main/java/gyro/azure/storage/PolicyDefinition.java
- src/main/java/gyro/azure/storage/PolicyFilter.java
- src/main/java/gyro/azure/storage/PolicyRule.java
- src/main/java/gyro/azure/storage/PolicySnapshot.java
- src/main/java/gyro/azure/storage/StorageAccountResource.java
- src/main/java/gyro/azure/storage/StorageLifeCycle.java
> Implement Lifecycle for Azure Storage.

- src/main/java/gyro/azure/package-info.java
> Credentials Implementation Documentation is Missing Steps

- CHANGELOG.md
- src/main/java/gyro/azure/compute/VirtualMachineResource.java
> Azure VirtualMachine should Implement GyroInstance

- CHANGELOG.md
- src/main/java/gyro/azure/compute/VMScaleSetResource.java
- src/main/java/gyro/azure/compute/VirtualMachineResource.java
> Expose object id for System Managed Identity on Virtual Machine and Scale Set resources

- CHANGELOG.md
- src/main/java/gyro/azure/storage/StorageAccountResource.java
> Storage account finder error

- CHANGELOG.md
- src/main/java/gyro/azure/compute/VirtualMachineResource.java
Fixes #82 
This PR updates the query for Availability Sets when creating a Virtual Machine.
> Applies Availability Set to Virtual Machine on Creation

- build.gradle
- src/main/java/gyro/azure/compute/DiskResource.java
- src/main/java/gyro/azure/storage/PolicyBaseBlob.java
- src/main/java/gyro/azure/storage/PolicySnapshot.java
> Update azure sdk from 1.27.0 to 1.30.0

- CHANGELOG.md
- src/main/java/gyro/azure/network/ApplicationGatewayResource.java
Fixes https://github.com/perfectsense/gyro-azure-provider/issues/107
Our deployment workflow relies on the health check results of the Application Gateway backend instances. This PR adds an API that returns a map of the backend instance states and their counts.
This allows counts to be accessible from the Gyro language, specifically workflows.
> Add Application Gateway Backend Health API

- src/main/java/gyro/azure/network/NicIpConfigurationResource.java
> Allow Application Security Groups to be Applied to VM's

- examples/compute/snapshot.gyro
- src/main/java/gyro/azure/keyvault/KeyVaultCertificateLifetimeAction.java
> Refactor examples

- CHANGELOG.md
- README.md
- build.gradle
- examples/.gyro/init.gyro
- src/main/java/gyro/azure/accessmanagement/package-info.java
- src/main/java/gyro/azure/cosmosdb/package-info.java
- src/main/java/gyro/azure/package-info.java
- src/main/java/gyro/azure/sql/package-info.java
> Cleanup for release 0.99.1

- build.gradle
> Update release build from 0.99.1 to 0.99.2

- src/main/java/gyro/azure/AzureCredentials.java
> Fix to honor subscription property.

- src/main/java/gyro/azure/CloudBlobContainerFileBackend.java
Fix #128 
~~Please note that this PR is based off of `feature/client-with-subscription` branch.~~
> Fix remote file backend.

- build.gradle
- src/main/java/gyro/azure/CloudBlobContainerFileBackend.java
> Optimization 5 & 6 - Add exists(String file) and copy(String source, String dest) methods to FileBackend

- CHANGELOG.md
- README.md
- src/main/java/gyro/azure/AbstractAzureCommand.java
- src/main/java/gyro/azure/AzureCommand.java
- src/main/java/gyro/azure/keyvault/AbstractVaultCommand.java
- src/main/java/gyro/azure/keyvault/AddVaultCertificateCommand.java
- src/main/java/gyro/azure/keyvault/AddVaultSecretCommand.java
- src/main/java/gyro/azure/keyvault/AzureKeyVaultCommand.java
- src/main/java/gyro/azure/keyvault/ListVaultCertificateCommand.java
- src/main/java/gyro/azure/keyvault/ListVaultSecretCommand.java
- src/main/java/gyro/azure/keyvault/RemoveVaultCertificateCommand.java
- src/main/java/gyro/azure/keyvault/RemoveVaultSecretCommand.java
- src/main/java/gyro/azure/network/AbstractApplicationGatewayCommand.java
- src/main/java/gyro/azure/network/AddApplicationGatewayCertificateCommand.java
- src/main/java/gyro/azure/network/AzureApplicationGatewayCommand.java
- src/main/java/gyro/azure/network/ImportApplicationGatewayCertificateCommand.java
- src/main/java/gyro/azure/network/ListApplicationGatewayCertificateCommand.java
- src/main/java/gyro/azure/network/RemoveApplicationGatewayCertificateCommand.java
- src/main/java/gyro/azure/package-info.java
Fixes #132 
Depends on https://github.com/perfectsense/gyro/pull/321
> Picocli implementation

- CHANGELOG.md
- build.gradle
> Prepare for development of version 0.99.3

- build.gradle
- src/main/java/gyro/azure/CloudBlobContainerFileBackend.java
> Use @uses-credentials to set custom credentials for filebackend

- build.gradle
- examples/registries/registry.gyro
- src/main/java/gyro/azure/AzureCredentials.java
- src/main/java/gyro/azure/AzureResource.java
- src/main/java/gyro/azure/AzureResourceManagerFinder.java
- src/main/java/gyro/azure/registries/RegistryFinder.java
- src/main/java/gyro/azure/registries/RegistryResource.java
- src/main/java/gyro/azure/registries/Webhook.java
- src/main/java/gyro/azure/registries/package-info.java
> Add registry resource

- src/main/java/gyro/azure/storage/StorageAccountResource.java
Allow public access for storage accounts
> Storage account public access
